version: '3.9'
services:
  jenkins:
    container_name: ikhsan_jenkins
    privileged: true
    image: ikhsan/jenkins:latest
    build:
      context: .
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.osx
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./jenkins-docker-certs:/certs/client:ro
    ports:
      - 8080:8080
      - 50000:50000
    restart: always
    networks:
      - jenkins
  docker-dnid:
    container_name: ikhsan_docker
    image: docker:dind
    privileged: true
    command: --storage-driver=overlay2
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./jenkins-docker-certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    ports:
      - 2376:2376
    networks:
      jenkins:
        aliases:
          - docker
networks:
  jenkins:
    name: jenkins
   
